### ISSUE TITLE
polygon的区域可以在地图上做个截图么？

### ISSUE THREAD

**Issue by mcheng315** [TinyQ/TQLocationConverter#5]
直接看点，不清楚到底覆盖了哪些区域。

**Comment by sxgfxm** [comment]
截图在这里最下面。
https://sxgfxm.github.io/blog/2016/10/19/iospan-duan-gpszuo-biao-shi-fou-zai-zhong-guo/
覆盖的区域也可以自己一个点一个点标出来，我只是标了一个大致的轮廓。
